sudo: required

dist: xenial

addons:

snaps:

- name: dotnet-sdk

confinement: classic

channel: lts/stable

language: csharp

dotnet: 3.1

mono: none

solution: FinalProjectRegistration.sln

before_script:

sudo snap alias dotnet-sdk.dotnet dotnet

script:
- dotnet restore
- dotnet build
- dotnet test
